name: Deploy code

on: ['workflow_dispatch']

jobs:
    deploy-code:
        name: Deploy code
        runs-on: ubuntu-latest
        env:
            repository: 'spatie/freek.dev'
            host: 'freek.dev'
            username: 'forge'
            currentDir: '/home/forge/freek-test.dev/current'

        steps:
            -   name: 💻 Deploying code changes
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ env.host }}
                    username: ${{ env.username }}
                    key: ${{ secrets.KEY }}
                    script: |
                        cd ${{ env.currentDir }}
                        git pull origin master
                        php artisan config:clear
                        php artisan view:clear
                        php artisan cache:clear
                        php artisan config:cache
                        php artisan responsecache:clear
                        php artisan schedule-monitor:sync
                        sudo supervisorctl restart all
                        sudo service php7.4-fpm restart
